apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-31T14:10:55Z"
  name: carts-primary
  resourceVersion: "85665"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 40e2db7f-fbe8-11e9-816c-42010a80017d
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts-primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
